"use-strict";

import * as fs from "fs";
import os = require("os");
import * as path from "path";
import * as vscode from "vscode";
import * as common from "./common";

// to-do: change the console output to another form of user notification prior to production release.
/* tslint:disable:no-console */
const docsAuthoringDirectory = path.join(os.homedir(), "Docs Authoring");
export const templateDirectory = path.join(docsAuthoringDirectory, "Templates");

// download a copy of the template repo to the "docs authoring" directory.  no .git-related files will be generated by this process.
export function downloadRepo() {
    const download = require("download-git-repo");
    const templateRepo = "MicrosoftDocs/content-templates";
    download(templateRepo, docsAuthoringDirectory, (err) => {
        if (err) {
            common.postWarning(err ? "Error: Cannot connect to " + templateRepo : "Success");
        }
    });
}

// the download process is on a repo-level so this function will be used to delete any files pulled down by the download process.
export function cleanupDownloadFiles() {
    fs.readdir(docsAuthoringDirectory, (err, files) => {
        files.forEach((file) => {
            const fullFilePath = path.join(docsAuthoringDirectory, file);
            fs.stat(path.join(fullFilePath), (error, stats) => {
                if (stats.isFile()) {
                    console.log(fullFilePath);
                    fs.unlinkSync(fullFilePath);
                }
                if (error) {
                    console.log("Error: " + error);
                }
            });
        });
    });
}
