export const repoMapping = [
	{ repoName: 'azure-docs', name: 'azure' },
	{ repoName: 'learn', name: 'Learn' },
	{ repoName: 'live-share', name: 'live-share' },
	{ repoName: 'virtualization-documentation', name: 'virtualization-documentation' },
	{ repoName: 'architecture-center', name: 'architecture-center' },
	{ repoName: 'windows-itpro-docs', name: 'windows' },
	{ repoName: 'powershell-docs', name: 'powershell' },
	{ repoName: 'windowsserverdocs', name: 'windows server' },
	{ repoName: 'sql-docs', name: 'sql' },
	{ repoName: 'cpp', name: 'C++' },
	{ repoName: 'intellicode', name: 'intellicode' },
	{ repoName: 'office-docs-powershell', name: 'powershell' },
	{ repoName: 'windows-uwp', name: 'uwp' },
	{ repoName: 'vsonline', name: 'online' },
	{ repoName: 'sccmdocs', name: 'sccm' },
	{ repoName: 'officedocs-sharepoint', name: 'sharepoint' },
	{ repoName: 'sysinternals', name: 'sysinternals' },
	{ repoName: 'dynamics-365-customer-engagement', name: 'dynamics-365' },
	{ repoName: 'WSL', name: 'WSL' },
	{ repoName: 'azure-docs', name: 'azure' },
	{ repoName: 'azure-docs-cli', name: 'azure-cli' },
	{ repoName: 'visualstudio-docs', name: 'visualstudio' },
	{ repoName: 'azure-dev-docs', name: 'azure' },
	{ repoName: 'cloud-adoption-framework', name: 'cloud-adoption-framework' },
	{ repoName: 'azure-stack-docs', name: 'azure' },
	{ repoName: 'edge-developer', name: 'edge' },
	{ repoName: 'xamarin-docs', name: 'xamarin' },
	{ repoName: 'microsoft-365-community', name: 'microsoft-365' },
	{ repoName: 'win32', name: 'win32' },
	{ repoName: 'vsts-docs', name: 'vsts' },
	{ repoName: 'cpp-docs', name: 'C++' },
	{ repoName: 'PowerShell-Docs', name: 'PowerShell' },
	{ repoName: 'typography-issues', name: 'typography-issues' },
	{ repoName: 'windows-powershell-docs', name: 'powershell' },
	{ repoName: 'powerbi-docs', name: 'powerbi' },
	{ repoName: 'windows-uwp', name: 'uwp' },
	{ repoName: 'OfficeDocs-SharePoint', name: 'SharePoint' },
	{ repoName: 'sdk-api', name: 'sdk-api' },
	{ repoName: 'quantum-docs-pr', name: 'quantum' },
	{ repoName: 'OData-docs', name: 'OData' },
	{ repoName: 'dynamics365smb-devitpro-pb', name: 'dynamics365' },
	{ repoName: 'msix-docs', name: 'msix-docs' },
	{ repoName: 'OfficeDocs-SkypeForBusiness', name: 'SkypeForBusiness' },
	{ repoName: 'power-platform', name: 'power-platform' },
	{ repoName: 'winrt-api', name: 'winrt-api' },
	{ repoName: 'dynamics-365-unified-operations-public', name: 'dynamics-365' },
	{ repoName: 'powerapps-docs', name: 'powerapps' },
	{ repoName: 'power-automate-docs', name: 'power-automate' },
	{ repoName: 'playfab-docs', name: 'playfab' },
	{ repoName: 'windows-driver-docs', name: 'windows-driver' },
	{ repoName: 'microsoft-qa-docs', name: 'microsoft-qa' },
	{ repoName: 'windows-itpro-docs', name: 'windows-itpro' },
	{ repoName: 'appcenter-docs', name: 'appcenter' },
	{ repoName: 'OfficeDocs-Enterprise', name: 'Enterprise' },
	{ repoName: 'OfficeDocs-ProjectServer', name: 'ProjectServer' },
	{ repoName: 'sql-docs', name: 'sql' },
	{ repoName: 'architecture-center', name: 'architecture-center' },
	{ repoName: 'bi-shared-docs', name: 'bi-shared' },
	{
		repoName: 'BusinessApplicationPlatform-Connectors-public',
		name: 'BusinessApplicationPlatform-Connectors'
	},
	{ repoName: 'partner-center-sdk', name: 'partner-center-sdk' },
	{ repoName: 'AdaptiveCards', name: 'AdaptiveCards' },
	{ repoName: 'msteams-docs', name: 'msteams' },
	{ repoName: 'microsoft-365-docs', name: 'microsoft-365' },
	{ repoName: 'office-docs-powershell', name: 'powershell' },
	{ repoName: 'azure-docs-sdk-python', name: 'azure' },
	{ repoName: 'windows-driver-docs-ddi', name: 'windows-driver' },
	{ repoName: 'office-365-management-api', name: 'office-365' },
	{ repoName: 'OfficeDocs-O365ITPro', name: 'O365ITPro' },
	{ repoName: 'windowsserverdocs', name: 'windows server' },
	{ repoName: 'windows-iotcore-docs', name: 'windows-iotcore' },
	{ repoName: 'Advertising-docs', name: 'Advertising' },
	{ repoName: 'Console-Docs', name: 'Console' },
	{ repoName: 'EdgeEnterprise', name: 'EdgeEnterprise' },
	{ repoName: 'SCCMdocs', name: 'SCCM' },
	{ repoName: 'dynamics365smb-docs', name: 'dynamics365' },
	{ repoName: 'intellicode', name: 'intellicode' },
	{ repoName: 'dynamics-365-ai', name: 'dynamics-365-ai' },
	{ repoName: 'Virtualization-Documentation', name: 'Virtualization' },
	{ repoName: 'dynamics-365-fraud-protection', name: 'dynamics-365' },
	{ repoName: 'OfficeDocs-DeployOffice', name: 'DeployOffice' },
	{ repoName: 'OfficeDocs-Support', name: 'Support' },
	{ repoName: 'winrt-related', name: 'winrt' },
	{ repoName: 'ATADocs', name: 'ATADocs' },
	{ repoName: 'forms-pro', name: 'forms-pro' },
	{ repoName: 'common-data-model-and-service', name: 'common-data-model-and-service' },
	{ repoName: 'live-share', name: 'live-share' },
	{ repoName: 'sysinternals', name: 'sysinternals' },
	{ repoName: 'dynamics-365-mixed-reality', name: 'dynamics-365' },
	{ repoName: 'pipelines-azureml', name: 'pipelines-azureml' },
	{ repoName: 'azure-docs-powershell', name: 'azure' },
	{
		repoName: 'office-developer-infopath-form-templates-ref-dotnet',
		name: 'office-developer-infopath-form-templates-ref-dotnet'
	},
	{ repoName: 'Azure-RMSDocs', name: 'Azure' },
	{ repoName: 'mixed-reality', name: 'mixed-reality' },
	{ repoName: 'cloud-developer-advocates', name: 'cloud-developer-advocates' },
	{ repoName: 'microsoft-academic-services', name: 'microsoft-academic-services' },
	{ repoName: 'feedback', name: 'feedback' },
	{ repoName: 'mslearn-aml-labs', name: 'mslearn-aml-labs' },
	{ repoName: 'WindowsCommunityToolkitDocs', name: 'WindowsCommunityToolkit' },
	{ repoName: 'bingmaps-docs', name: 'bingmaps' },
	{ repoName: 'mslearn-live-migrating-to-the-cloud', name: 'mslearn-live-migrating-to-the-cloud' },
	{ repoName: 'azure-reference-other', name: 'azure' },
	{ repoName: 'memdocs', name: 'mem' },
	{ repoName: 'sccm-docs-powershell-ref', name: 'sccm' },
	{
		repoName: 'mslearn-tailspin-spacegame-web-automate',
		name: 'mslearn-tailspin-spacegame-web-automate'
	},
	{ repoName: 'vsts-rest-api-specs', name: 'vsts-rest-api-specs' },
	{ repoName: '.github', name: '.github' },
	{ repoName: 'OfficeDocs-Exchange', name: 'Exchange' },
	{ repoName: 'CloudAppSecurityDocs', name: 'CloudAppSecurity' },
	{ repoName: 'IntuneDocs', name: 'Intune' },
	{ repoName: 'biztalk-docs', name: 'biztalk' },
	{ repoName: 'cognitive-toolkit-docs', name: 'cognitive-toolkit' },
	{ repoName: 'powerquery-docs', name: 'powerquery' },
	{ repoName: 'windows-ai-docs', name: 'windows-ai' },
	{ repoName: 'VBA-Docs', name: 'VBA' },
	{ repoName: 'pipelines-multistage', name: 'pipelines-multistage' },
	{
		repoName: 'mslearn-expose-hybrid-services-with-azure-relay',
		name: 'mslearn-expose-hybrid-services-with-azure-relay'
	},
	{ repoName: 'pipelines-dotnet-core-docker', name: 'pipelines-dotnet-core-docker' },
	{
		repoName: 'mslearn-tailspin-spacegame-web-azure-functions',
		name: 'mslearn-tailspin-spacegame-web-azure-functions'
	},
	{ repoName: 'pipelines-dotnet-core', name: 'pipelines-dotnet-core' },
	{ repoName: 'pipelines-java', name: 'pipelines-java' },
	{ repoName: 'windows-insider', name: 'windows-insider' },
	{ repoName: 'office-developer-client-docs', name: 'office-developer-client' },
	{ repoName: 'office-developer-exchange-docs', name: 'office-developer-exchange' },
	{ repoName: 'mixedreality-enthusiast-guide', name: 'mixedreality-enthusiast-guide' },
	{ repoName: 'partner-center-java-docs', name: 'partner-center-java' },
	{ repoName: 'pipelines-javascript', name: 'pipelines-javascript' },
	{ repoName: 'xbox-live-docs', name: 'xbox-live' },
	{ repoName: 'data-integration', name: 'data-integration' },
	{ repoName: 'azure-docs-sdk-node', name: 'azure' },
	{ repoName: 'Contribute', name: 'Contribute' },
	{ repoName: 'msftdynamicsgpdocs', name: 'dynamics' },
	{ repoName: 'vsonline', name: 'vsonline' },
	{ repoName: 'microsoft-style-guide', name: 'microsoft-style-guide' },
	{ repoName: 'ms-learn-ml-crash-course-python', name: 'Learn' },
	{ repoName: 'bot-docs', name: 'bot' },
	{ repoName: 'navdevitpro-content-pr', name: 'navdevitpro' },
	{ repoName: 'iis-docs', name: 'iis' },
	{ repoName: 'mslearn-tailspin-spacegame-web-deploy', name: 'Learn' },
	{ repoName: 'WDAC-Toolkit', name: 'WDAC-Toolkit' },
	{ repoName: 'mslearn-build-api-azure-functions', name: 'Learn' },
	{ repoName: 'dynamics365-docs-odata-apis', name: 'dynamics365' },
	{ repoName: 'rd-pr', name: 'rd-pr' },
	{ repoName: 'OfficeDocs-MicrosoftSearch', name: 'MicrosoftSearch' },
	{ repoName: 'mslearn-protect-apis-on-api-management', name: 'Learn' },
	{ repoName: 'mslearn-improve-api-performance-with-apim-caching-policy', name: 'Learn' },
	{ repoName: 'open_specs_blog', name: 'open_specs_blog' },
	{ repoName: 'mslearn-the-mojifier', name: 'Learn' },
	{ repoName: 'office-shared-ref-docs', name: 'office' },
	{ repoName: 'MigrationPlaybookContent', name: 'MigrationPlaybookContent' },
	{ repoName: 'mslearn-tailspin-spacegame-web', name: 'Learn' },
	{ repoName: 'nav-content', name: 'nav' },
	{ repoName: 'bacx-pr', name: 'bacx' },
	{ repoName: 'mslearn-build-ml-model-with-azure-stream-analytics', name: 'Learn' },
	{ repoName: 'trace-processor-docs', name: 'trace-processor' },
	{ repoName: 'trace-processor-reference-docs', name: 'trace-processor-reference' },
	{ repoName: 'enterprise-graph-docs-pr', name: 'enterprise-graph' },
	{ repoName: 'azure-iot-docs-sdk-typescript', name: 'azure' },
	{ repoName: 'mslearn-aks-workshop-ratings-web', name: 'Learn' },
	{ repoName: 'partner-rest', name: 'partner-rest' },
	{ repoName: 'pipelines-xcode', name: 'pipelines-xcode' },
	{ repoName: 'mslearn-xamarin-ios-intro', name: 'Learn' },
	{ repoName: 'vs-tutorials', name: 'vs-tutorials' },
	{ repoName: 'OfficeDocs-O365ServiceDescriptions', name: 'O365ServiceDescriptions' },
	{ repoName: 'terminal', name: 'terminal' },
	{ repoName: 'IIS.Administration-docs', name: 'IIS' },
	{ repoName: 'mvp-hackadoc-2018', name: 'mvp-hackadoc-2018' },
	{ repoName: 'PlayReady', name: 'PlayReady' },
	{
		repoName: 'mslearn-troubleshoot-inbound-network-connectivity-azure-load-balancer',
		name: 'Learn'
	},
	{ repoName: 'EMDocs', name: 'EM' },
	{ repoName: 'oufr-dev-docs', name: 'oufr-dev' },
	{ repoName: 'mslearn-xamarin-android-intro', name: 'Learn' },
	{ repoName: 'DocsContentNav', name: 'DocsContentNav' },
	{
		repoName: 'office-developer-exchange-ews-proxy-ref-dotnet',
		name: 'office-developer-exchange-ews-proxy-ref-dotnet'
	},
	{ repoName: 'SecurityBenchmarks', name: 'SecurityBenchmarks' },
	{ repoName: 'pipelines-anaconda', name: 'pipelines-anaconda' },
	{ repoName: 'D365-FO-iCMSTest', name: 'D365' },
	{ repoName: 'ms-learn-ml-crash-course-R', name: 'Learn' },
	{ repoName: 'mslearn-control-access-to-azure-storage-with-sas', name: 'Learn' },
	{ repoName: 'ai-builder', name: 'ai-builder' },
	{ repoName: 'tensorflow', name: 'tensorflow' },
	{ repoName: 'CNTK', name: 'CNTK' },
	{ repoName: 'MIMDocs', name: 'MIM' },
	{ repoName: 'java-sandbox', name: 'java-sandbox' },
	{ repoName: 'mslearn-xamarin-forms-ui-with-xaml', name: 'Learn' },
	{ repoName: 'mslearn-aspnet-core', name: 'Learn' },
	{ repoName: 'visualfsharpdocs', name: 'visualfsharp' },
	{ repoName: 'docslocfeedback', name: 'docslocfeedback' },
	{ repoName: 'OfficeDocs-OfficeOnlineServer', name: 'OfficeOnlineServer' },
	{ repoName: 'azure-devops-server-docs', name: 'azure-devops' },
	{ repoName: 'mslearn-migrate-sql-server-relational-data', name: 'Learn' },
	{ repoName: 'TeamBlogFeedback', name: 'TeamBlogFeedback' },
	{ repoName: 'mslearn-live-azure-fundamentals', name: 'Learn' },
	{ repoName: 'pipelines-android', name: 'pipelines-android' },
	{ repoName: 'pipelines-python-django', name: 'pipelines-python-django' },
	{ repoName: 'azure-gaming-docs', name: 'azure' },
	{ repoName: 'CortanaSkillsKit', name: 'CortanaSkillsKit' },
	{ repoName: 'azure-java-reference', name: 'azure' },
	{ repoName: 'mslearn-remotely-monitor-and-control-devices-with-iot-hub', name: 'Learn' },
	{ repoName: 'curtcu-samples', name: 'curtcu' },
	{ repoName: 'mslearn-provision-infrastructure-azure-pipelines', name: 'Learn' },
	{ repoName: 'mslearn-create-publish-static-serverless-website', name: 'Learn' },
	{ repoName: 'kaizala-docs', name: 'kaizala' },
	{ repoName: 'aog_codesample', name: 'aog_codesample' },
	{ repoName: 'codecoverage-yaml-samples', name: 'codecoverage-yaml-samples' },
	{ repoName: 'OfficeDocs-WorkplaceAnalytics', name: 'WorkplaceAnalytics' },
	{ repoName: 'OfficeDocs-CustomLearning', name: 'CustomLearning' },
	{ repoName: 'mslearn-publish-manage-apis-with-azure-api-management', name: 'Learn' },
	{ repoName: 'LogAnalyticsExamples', name: 'LogAnalyticsExamples' },
	{ repoName: 'mslearn-data-anomaly-detection-using-azure-iot-hub', name: 'Learn' },
	{ repoName: 'msrd-dev-center', name: 'msrd-dev-center' },
	{ repoName: 'mslearn-advocates.azure-functions-and-signalr', name: 'Learn' },
	{ repoName: 'azure-cloud-services-files', name: 'azure' },
	{ repoName: 'powerbi-docs-powershell', name: 'powerbi' },
	{ repoName: 'mslearn-build-ai-web-app-with-python-and-flask', name: 'Learn' },
	{ repoName: 'machine-learning-server-docs', name: 'machine-learning-server-docs' },
	{ repoName: 'mslearn-xamarin-forms-customize-listview', name: 'Learn' },
	{ repoName: 'mslearn-xamarin-forms-use-effects', name: 'Learn' },
	{ repoName: 'project-rome', name: 'project-rome' },
	{ repoName: 'botbuilder-docs-sdk-typescript', name: 'botbuilder-docs-sdk-typescript' },
	{ repoName: 'mslearn-azure-data-platform-workshop', name: 'Learn' },
	{ repoName: 'partner-center-docs-powershell', name: 'partner-center-docs-powershell' },
	{ repoName: 'CordovaDocs', name: 'CordovaDocs' },
	{ repoName: 'winui-api', name: 'winui-api' },
	{ repoName: 'windows-topic-specific-samples', name: 'windows-topic-specific-samples' },
	{ repoName: 'botbuilder-docs-sdk-python', name: 'botbuilder-docs-sdk-python' },
	{ repoName: 'mslearn-connect-services-together', name: 'Learn' },
	{ repoName: 'OfficeDocs-M365FreelanceToolkit-pr', name: 'M365FreelanceToolkit' },
	{ repoName: 'mslearn-build-a-web-app-with-mean-on-a-linux-vm', name: 'Learn' },
	{ repoName: 'devops-learn-pr', name: 'Learn' },
	{ repoName: 'mslearn-aks-workshop-ratings-api', name: 'Learn' },
	{ repoName: 'pipelines-javascript-docker', name: 'pipelines-javascript-docker' },
	{ repoName: 'mslearn-tailspin-spacegame-web-models', name: 'Learn' },
	{ repoName: 'mslearn-azure-pipelines-build-agent', name: 'Learn' },
	{ repoName: 'cordova-docs', name: 'cordova-docs' },
	{ repoName: 'Azure-Industry-archive-docs', name: 'Azure-Industry-archive-docs' },
	{ repoName: 'message-analyzer-docs-pr', name: 'message-analyzer-docs-pr' },
	{ repoName: 'DynamicsAX2012-technet', name: 'DynamicsAX2012-technet' },
	{ repoName: 'mslearn-developer-tools-power-platform', name: 'Learn' },
	{ repoName: 'mslearn-build-azure-vm-templates', name: 'Learn' },
	{ repoName: 'pipelines-go', name: 'pipelines-go' },
	{ repoName: 'mslearn-process-images-with-the-computer-vision-service', name: 'Learn' },
	{ repoName: 'devops-resource-center', name: 'devops-resource-center' },
	{ repoName: 'mslearn-build-app-solution', name: 'Learn' },
	{ repoName: 'D365-CE-iCMSTest', name: 'D365-CE-iCMSTest' },
	{ repoName: 'mslearn-apps-and-batch', name: 'Learn' },
	{ repoName: 'mslearn-your-first-iot-central-app', name: 'Learn' },
	{ repoName: 'mslearn-text-analytics', name: 'Learn' },
	{ repoName: 'mslearn-deploy-vms-from-vhd-templates', name: 'Learn' },
	{ repoName: 'mslearn-xamarin-forms-create-mobile-app', name: 'Learn' },
	{ repoName: 'mslearn-create-data-pipelines-using-databricks-delta', name: 'Learn' },
	{ repoName: 'mslearn-n-tier-architecture', name: 'Learn' },
	{ repoName: 'npmingest_ts', name: 'npmingest_ts' },
	{ repoName: 'mslearn-perform-basic-data-transformation-in-azure-databricks', name: 'Learn' },
	{ repoName: 'mslearn-azure-databricks-notebooks-fundamentals', name: 'Learn' },
	{ repoName: 'AzureStack-Tools', name: 'AzureStack-Tools' },
	{ repoName: 'mslearn-store-data-in-azure', name: 'Learn' },
	{ repoName: 'Microsoft-MPI', name: 'Microsoft-MPI' },
	{ repoName: 'mslearn-xamarin-forms-stack-tab-navigation', name: 'Learn' },
	{ repoName: 'OfficeDocs-o365seccomp', name: 'OfficeDocs-o365seccomp' },
	{ repoName: 'labs', name: 'labs' },
	{ repoName: 'IntuneEDU', name: 'IntuneEDU' },
	{ repoName: 'office-developer-msproject-xml-docs', name: 'office' },
	{ repoName: 'groove-api-documentation', name: 'groove-api-documentation' },
	{ repoName: 'mslearn-monitor-diagnose-and-troubleshoot-azure-storage', name: 'Learn' },
	{ repoName: 'mslearn-extend-share-capacity-with-azure-file-sync', name: 'Learn' },
	{ repoName: 'mslearn-protect-infrastructure-with-azure-site-recovery', name: 'Learn' },
	{ repoName: 'mslearn-hub-and-spoke-network-architecture', name: 'Learn' },
	{ repoName: 'mslearn-host-domain-azure-dns', name: 'Learn' },
	{ repoName: 'mslearn-choose-compute-provisioning', name: 'Learn' },
	{ repoName: 'seller-center', name: 'seller-center' },
	{ repoName: 'office-lync-ref-docs', name: 'office-lync' },
	{ repoName: 'globalization', name: 'globalization' },
	{ repoName: 'azure-sphere-issues', name: 'azure' },
	{ repoName: 'azure-monitor-health-knowledge', name: 'azure' },
	{ repoName: 'azure-devops-extensions', name: 'azure-devops' },
	{ repoName: 'D365-BC-iCMSTest', name: 'D365-BC-iCMSTest' },
	{ repoName: 'StickyNotes', name: 'StickyNotes' },
	{ repoName: 'windows-itpro-docs-migration', name: 'windows-itpro' },
	{ repoName: 'configmgr-dev', name: 'configmgr' },
	{ repoName: 'mslearn-control-authentication-with-apim', name: 'Learn' },
	{ repoName: 'projectfreta-docs-rest-apis', name: 'projectfreta-docs-rest-apis' },
	{ repoName: 'OfficeDocs-OfficeUpdates', name: 'OfficeUpdates' },
	{ repoName: 'mslearn-xamarin-store-data-sqlite', name: 'Learn' },
	{ repoName: 'MicrosoftCollaboratePortal', name: 'MicrosoftCollaboratePortal' },
	{ repoName: 'mslearn-apim-and-functions', name: 'Learn' },
	{ repoName: 'intelligent-asset-manager', name: 'intelligent-asset-manager' },
	{ repoName: 'licensed-hardware', name: 'licensed-hardware' },
	{ repoName: 'office-developer-lync-evergreen-docs', name: 'office-developer-lync-evergreen' },
	{ repoName: 'docsplayground', name: 'docsplayground' },
	{ repoName: 'Azure-IoT-C-SDK-Reference', name: 'Azure-IoT-C-SDK-Reference' },
	{ repoName: 'Kaizala-ITPro-docs', name: 'Kaizala-ITPro-docs' },
	{ repoName: 'mslearn-hotel-reservation-system', name: 'Learn' },
	{ repoName: 'mslearn-continuous-deploy-serverless-web-app-devops', name: 'Learn' },
	{ repoName: 'hdinsight-kafka-rest-proxy', name: 'hdinsight-kafka-rest-proxy' },
	{ repoName: 'DevOpsLearn', name: 'DevOpsLearn' },
	{ repoName: 'mslearn-microservices-architecture', name: 'Learn' },
	{ repoName: 'OfficeDocs-FastTrack', name: 'FastTrack' },
	{ repoName: 'OfficeDocs-AppCompliance', name: 'AppCompliance' },
	{ repoName: 'OfficeDocs-AgentUniversity', name: 'AgentUniversity' },
	{ repoName: 'pipelines-xamarin', name: 'pipelines-xamarin' },
	{ repoName: 'mslearn-distribute-load-with-traffic-manager', name: 'Learn' },
	{ repoName: 'mslearn-read-and-write-data-using-azure-databricks', name: 'Learn' },
	{ repoName: 'patterns-practices', name: 'patterns-practices' },
	{ repoName: 'AIBuilder', name: 'AIBuilder' },
	{ repoName: 'PowerShell-Docs-archive', name: 'PowerShell-Docs-archive' },
	{ repoName: 'mslearn-improve-api-developer-experience-with-swagger', name: 'Learn' },
	{ repoName: 'intellisense-loc', name: 'intellisense-loc' },
	{ repoName: 'CSIDev-Public', name: 'CSIDev-Public' },
	{ repoName: 'mslearn-exploratory-data-analysis', name: 'Learn' },
	{
		repoName: 'mslearn-create-data-visualizations-using-azure-databricks-and-power-bi',
		name: 'Learn'
	},
	{ repoName: 'mslearn-streaming-in-azure-databricks', name: 'Learn' },
	{ repoName: 'mslearn-understanding-the-sql-dw-connector-with-azure-databricks', name: 'Learn' },
	{ repoName: 'sandbox', name: 'sandbox' },
	{ repoName: 'azure-rest-api-specs', name: 'azure' },
	{ repoName: 'blockchainv1-docs-rest-apis', name: 'blockchainv1-docs-rest-apis' },
	{ repoName: 'azure-iot-sdk-csharp', name: 'azure' },
	{ repoName: 'azure-blockchain-workbenchV1-docs-rest-apis', name: 'azure' },
	{ repoName: 'Office365DSC', name: 'Office365DSC' },
	{ repoName: 'mslearn-build-node-cosmos-app-vscode', name: 'Learn' },
	{ repoName: 'mslearn-deploy-run-container-app-service', name: 'Learn' },
	{ repoName: 'azure-pipelines-canary-k8s', name: 'azure-pipelines-canary-k8s' },
	{ repoName: 'mslearn-troubleshoot-azure-network-infrastructure', name: 'Learn' },
	{ repoName: 'mslearn-xamarin-consume-rest-services', name: 'Learn' },
	{ repoName: 'mslearn-xamarin-forms-xaml-resources-styles', name: 'Learn' },
	{ repoName: 'mslearn-write-internet-connected-Windows-apps', name: 'Learn' },
	{ repoName: 'webvr', name: 'webvr' },
	{
		repoName: 'office-developer-infopath-ref-dotnet',
		name: 'office-developer-infopath-ref-dotnet'
	},
	{
		repoName: 'office-developer-project-class-web-ref-dotnet',
		name: 'office-developer-project-class-web-ref-dotnet'
	},
	{
		repoName: 'office-developer-sharepoint-csom-ref-dotnet',
		name: 'office-developer-sharepoint-csom-ref-dotnet'
	},
	{
		repoName: 'office-developer-sharepoint-excel-ref-dotnet',
		name: 'office-developer-sharepoint-excel-ref-dotnet'
	},
	{
		repoName: 'office-developer-sharepoint-visio-ref-dotnet',
		name: 'office-developer-sharepoint-visio-ref-dotnet'
	},
	{
		repoName: 'office-developer-lync-persistent-chat-ref-dotnet',
		name: 'office-developer-lync-persistent-chat-ref-dotnet'
	},
	{
		repoName: 'office-developer-lync-silverlight-ref-dotnet',
		name: 'office-developer-lync-silverlight-ref-dotnet'
	},
	{
		repoName: 'office-developer-lync-wfp-ref-dotnet',
		name: 'office-developer-lync-wfp-ref-dotnet'
	},
	{
		repoName: 'office-developer-lync-client-ref-dotnet',
		name: 'office-developer-lync-client-ref-dotnet'
	},
	{
		repoName: 'office-developer-exchange-ews-managed-api-ref-dotnet',
		name: 'office-developer-exchange-ews-managed-api-ref-dotnet'
	},
	{
		repoName: 'office-developer-excel-pia-ref-dotnet',
		name: 'office-developer-excel-pia-ref-dotnet'
	},
	{
		repoName: 'office-developer-infopath-external-automation-ref-dotnet',
		name: 'office-developer-infopath-external-automation-ref-dotnet'
	},
	{ repoName: 'mipsdk-dotnet', name: 'mipsdk-dotnet' },
	{
		repoName: 'office-developer-managed-sip-api-ref-dotnet',
		name: 'office-developer-managed-sip-api-ref-dotnet'
	},
	{
		repoName: 'office-developer-o365-service-communications-ref-dotnet',
		name: 'office-developer-o365-service-communications-ref-dotnet'
	},
	{
		repoName: 'office-developer-office-pia-ref-dotnet',
		name: 'office-developer-office-pia-ref-dotnet'
	},
	{
		repoName: 'office-developer-outlook-pia-ref-dotnet',
		name: 'office-developer-outlook-pia-ref-dotnet'
	},
	{
		repoName: 'office-developer-ucma-api-ref-dotnet',
		name: 'office-developer-ucma-api-ref-dotnet'
	},
	{
		repoName: 'office-developer-ucma-voice-ref-dotnet',
		name: 'office-developer-ucma-voice-ref-dotnet'
	},
	{
		repoName: 'office-developer-word-pia-ref-dotnet',
		name: 'office-developer-word-pia-ref-dotnet'
	},
	{ repoName: 'hpc-docs-sdk-dotnet', name: 'hpc-docs-sdk-dotnet' },
	{ repoName: 'healthvault-docs', name: 'healthvault-docs' },
	{ repoName: 'azure-devops-docs-sdk-dotnet', name: 'azure-devops-docs-sdk-dotnet' },
	{ repoName: 'mslearn-xamarin-forms-mvvm-viewmodel', name: 'Learn' },
	{ repoName: 'mslearn-store-access-data-cosmos-table-api', name: 'Learn' },
	{ repoName: 'powerapps-docs-rest-apis', name: 'powerapps-docs-rest-apis' },
	{ repoName: 'mslearn-improve-app-scalability-resiliency-with-load-balancer', name: 'Learn' },
	{ repoName: 'archive-template', name: 'archive-template' },
	{ repoName: 'mslearn-handle-transient-errors-in-your-app', name: 'Learn' },
	{ repoName: 'mslearn-xamarin-forms-customize-xaml-layout', name: 'Learn' },
	{ repoName: 'pipelines-php', name: 'pipelines-php' },
	{ repoName: 'SamplesPages', name: 'SamplesPages' },
	{ repoName: 'azure-docs-sdk-go', name: 'azure' },
	{ repoName: 'mslearn-develop-app-that-queries-azure-sql', name: 'Learn' },
	{ repoName: 'mslearn-data-ingestion-with-azure-data-factory', name: 'Learn' },
	{ repoName: 'mslearn-build-chat-bot-with-azure-bot-service', name: 'Learn' },
	{ repoName: 'mslearn-route-and-process-data-logic-apps', name: 'Learn' },
	{ repoName: 'opsmgr-docs-rest-apis', name: 'opsmgr-docs-rest-apis' },
	{ repoName: 'mslearn-xamarin-forms-custom-renderers', name: 'Learn' },
	{ repoName: 'mslearn-secure-app-with-oidc-and-azure-ad', name: 'Learn' },
	{ repoName: 'vs-tutorial-samples', name: 'vs-tutorial-samples' },
	{ repoName: 'mslearn-create-cdn-static-resources-blob-storage', name: 'Learn' },
	{ repoName: 'pipelines-java-function', name: 'pipelines-java-function' },
	{ repoName: 'azure-devops-docs-sdk-web', name: 'azure-devops-docs-sdk-web' },
	{ repoName: 'mslearn-logic-apps-and-arm-templates', name: 'Learn' },
	{ repoName: 'mslearn-test-in-deployment-with-production-slots', name: 'Learn' },
	{ repoName: 'DocYamlAuthoringDemo', name: 'DocYamlAuthoringDemo' },
	{ repoName: 'MSLearn-CSharpFirstApplication', name: 'Learn' },
	{ repoName: 'Azure-MachineLearning-DataScience', name: 'Azure' },
	{ repoName: 'XboxLive-API', name: 'XboxLive' },
	{ repoName: 'mslearn-xamarin-forms-master-detail-navigation', name: 'Learn' },
	{ repoName: 'dotnet-archive', name: 'dotnet-archive' },
	{ repoName: 'mslearn-xamarin-forms-listview', name: 'Learn' },
	{ repoName: 'fslogix-docs', name: 'fslogix' },
	{ repoName: 'mslearn-xamarin-forms-design-patterns', name: 'Learn' },
	{ repoName: 'OfficeEDU', name: 'OfficeEDU' },
	{ repoName: 'mslearn-organize-blobs-properties-metadata', name: 'Learn' },
	{ repoName: 'graph-yaml-sample', name: 'graph-yaml' },
	{ repoName: 'mslearn-monitor-azure-cosmos-db', name: 'Learn' },
	{ repoName: 'prose-py-api-docs', name: 'prose-py-api' },
	{ repoName: 'mslearn-end-to-end-encryption-with-app-gateway', name: 'Learn' },
	{ repoName: 'mslearn-capture-application-logs-app-service', name: 'Learn' },
	{ repoName: 'mslearn-welcome-to-azure', name: 'Learn' },
	{ repoName: 'mslearn-authenticate-apps-with-managed-identities', name: 'Learn' },
	{ repoName: 'mslearn-ha-application-storage-with-grs', name: 'Learn' },
	{ repoName: 'mslearn-xamarin-forms-data-binding', name: 'Learn' },
	{ repoName: 'MachineLearning-Python-Feedback', name: 'MachineLearning-Python-Feedback' },
	{ repoName: 'mslearn-introduction-to-azure-search', name: 'Learn' },
	{ repoName: 'mslearn-create-an-app-to-run-parallel-compute-jobs-in-azure-batch', name: 'Learn' },
	{ repoName: 'mslearn-copy-move-blobs-from-containers-or-storage-accounts', name: 'Learn' },
	{ repoName: 'cognitive-toolkit-docs-python', name: 'cognitive-toolkit-docs-python' },
	{ repoName: 'pipelines-go-docker', name: 'pipelines-go-docker' },
	{ repoName: 'mslearn-diagnose-performance-with-application-insights', name: 'Learn' },
	{ repoName: 'mslearn-load-balance-web-traffic-with-application-gateway', name: 'Learn' },
	{ repoName: 'SpeechServicePrivatePreview', name: 'SpeechServicePrivatePreview' },
	{ repoName: 'Speech', name: 'Speech' },
	{ repoName: 'mslearn-access-blob-storage-metrics-from-code', name: 'Learn' },
	{ repoName: 'mslearn-secure-and-isolate-with-nsg-and-service-endpoints', name: 'Learn' },
	{ repoName: 'azure-cosmos-db-graph-dotnet-getting-started', name: 'azure' },
	{ repoName: 'groove-api-sdk-csharp', name: 'groove-api-sdk-csharp' },
	{ repoName: 'functions-dotnet-codercards', name: 'functions-dotnet-codercards' },
	{ repoName: 'Microsoft-teams-docs', name: 'Microsoft-teams' },
	{ repoName: 'mslearn-logic-apps-and-custom-connectors', name: 'Learn' },
	{ repoName: 'mslearn-optimize-blob-storage-costs', name: 'Learn' },
	{ repoName: 'mslearn-win32uwp', name: 'Learn' },
	{ repoName: 'mslearn-support-concurrency-blob-storage', name: 'Learn' },
	{ repoName: 'learn-test-pr', name: 'Learn' },
	{ repoName: 'learn-template', name: 'Learn' },
	{ repoName: 'd365Ops-Financials', name: 'Financials' },
	{ repoName: 'mslearn-load-test-web-app-azure-devops', name: 'Learn' },
	{ repoName: 'mslearn-add-and-size-disks-in-azure-virtual-machines', name: 'Learn' },
	{ repoName: 'mslearn-work-with-vision-cognitive-services', name: 'Learn' },
	{ repoName: 'D365-NAV-iCMSTest', name: 'D365-NAV-iCMSTest' },
	{ repoName: 'mslearn-perform-advanced-data-transformation-in-azure-databricks', name: 'Learn' },
	{ repoName: 'mslearb-perform-advanced-data-transformation-in-azure-databricks', name: 'Learn' },
	{ repoName: 'mslearn-implement-azure-sql-data-warehouse', name: 'Learn' },
	{ repoName: 'mslearn-deep-learning', name: 'Learn' },
	{ repoName: 'mslearn-model-training-selection-evaluation', name: 'Learn' },
	{ repoName: 'content-templates', name: 'content-templates' },
	{ repoName: 'ONNXRuntime-Docs', name: 'ONNXRuntime' },
	{ repoName: 'pipelines-ruby', name: 'pipelines-ruby' },
	{ repoName: 'java-ref-template', name: 'java-ref-template' },
	{ repoName: 'Azure-Non-standard-emails', name: 'Azure-Non-standard-emails' },
	{ repoName: 'odata-sandbox', name: 'odata-sandbox' },
	{ repoName: 'Microbuild.Core', name: 'Microbuild.Core' },
	{ repoName: 'mslearn-create-neural-network-with-dsvm', name: 'Learn' },
	{ repoName: 'dynamics365hubpages.pt', name: 'dynamics365hubpages.pt' },
	{ repoName: 'rest-ref-template', name: 'rest-ref-template' },
	{ repoName: 'windowstc', name: 'windowstc' },
	{ repoName: 'mslearn-classify-images-with-the-custom-vision-service', name: 'Learn' },
	{
		repoName: 'office-developer-sharepoint-server-2013-ref-dotnet',
		name: 'office-developer-sharepoint-server-2013-ref-dotnet'
	},
	{ repoName: 'sphinx-docfx-yaml-docs', name: 'sphinx-docfx-yaml-docs' },
	{ repoName: 'KinsmanRepoTemp', name: 'KinsmanRepoTemp' },
	{ repoName: 'DynamicsAX2012-msdn', name: 'DynamicsAX2012-msdn' },
	{ repoName: 'OfficeDocs-OfficeOnlineServer-Test-pr', name: 'OfficeOnlineServer' },
	{ repoName: 'CLI-Xref', name: 'CLI-Xref' },
	{ repoName: 'gestures-docs', name: 'gestures-docs' },
	{ repoName: 'sandbox-bus-app-relnote', name: 'sandbox-bus-app-relnote' },
	{ repoName: 'botbuilder-dotnet', name: 'botbuilder-dotnet' },
	{ repoName: 'UWP-getstarted', name: 'UWP' },
	{ repoName: 'uwp-get-started', name: 'uwp' },
	{ repoName: 'dotnet-xref', name: 'dotnet' },
	{ repoName: 'ObjectiveC-ref-template', name: 'ObjectiveC' },
	{ repoName: 'msteam-docs-sdk-typescript', name: 'msteam-docs-sdk-typescript' },
	{ repoName: 'vsts-rest', name: 'vsts' },
	{ repoName: 'MusicStoreSample', name: 'MusicStoreSample' },
	{ repoName: 'PowerShell-DSC-for-Linux', name: 'PowerShell' },
	{ repoName: 'sql-managed-reference-pr-xref', name: 'sql' },
	{ repoName: 'Reporting-Services', name: 'Reporting-Services' }
];
