name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@1.5
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "ceapex"
          ado_project: "Engineering"
          ado_area_path: "Engineering\\Authoring"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_close_state: "Closed"
          ado_bypassrules: true
